'use strict';
const assert = require('assert');
process.env.EXECUTION_MODE = 'analysis';
process.env.AI_LEVERAGE_OPTIONS = '1,2,3,5,100';
process.env.MAX_AI_LEVERAGE = '5';
process.env.DAILY_SOFT_TARGET_PCT = '2';
process.env.DAILY_HARD_TARGET_PCT = '5';
process.env.SOFT_TARGET_RISK_MULTIPLIER = '0.5';
process.env.SOFT_TARGET_MAX_LEVERAGE = '2';
process.env.AI_CIRCUIT_BASE_MS = '15000';
process.env.AI_CIRCUIT_MAX_MS = '300000';
const { config, validateConfig } = require('../src/core/config');
assert.deepStrictEqual([...config.risk.allowedLeverages], [1, 2, 3, 5]);
assert.strictEqual(config.risk.maxLeverage, 5);
assert.strictEqual(config.app.executionMode, 'analysis');
assert.strictEqual(config.targets.softPct, 2);
assert.strictEqual(config.targets.hardPct, 5);
assert.strictEqual(config.targets.softRiskMultiplier, 0.5);
assert.strictEqual(config.targets.softMaxLeverage, 2);
assert.strictEqual(config.ai.circuitBaseMs, 15000);
assert.strictEqual(config.ai.circuitMaxMs, 300000);
assert.strictEqual(validateConfig().valid, true);
console.log('config hard caps and targets verified');
