'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'v16-db-'));
process.env.TRADING_DB_PATH = path.join(dir, 'trading.db');
const db = require('../src/database');
db.saveTrade({ tradeId: 'same-close', coin: 'BTC', side: 'BUY', pnl: 1, status: 'closed' });
db.saveTrade({ tradeId: 'same-close', coin: 'BTC', side: 'BUY', pnl: 2, status: 'closed' });
const rows = db.db.prepare('SELECT * FROM trades WHERE tradeId = ?').all('same-close');
assert.strictEqual(rows.length, 1);
assert.strictEqual(rows[0].pnl, 2);
db.savePosition({ coin: 'ETH', side: 'buy', entryPrice: 100, size: 1, status: 'OPEN' });
db.savePosition({ coin: 'ETH', side: 'buy', entryPrice: 101, size: 2, status: 'OPEN' });
assert.strictEqual(db.getOpenPositions().length, 1);
assert.strictEqual(db.getOpenPositions()[0].entryPrice, 101);
db.close();
console.log('database idempotency and position upsert verified');
