'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'v16-risk-'));
process.env.EXECUTION_MODE = 'analysis';
process.env.DATA_DIR = dir;
process.env.RISK_STATE_FILE = path.join(dir, 'risk.json');
const risk = require('../src/risk_manager');
risk.setEquity(10000);
risk.recordOpenedTrade({ coin: 'ETH/USDT:USDT', equity: 10000, openedAtMs: 123456 });
assert.strictEqual(risk.getLastTradeTime('ETHUSDT'), 123456);
assert.strictEqual(risk.getStatus().tradesOpenedToday, 1);
let newly = risk.reconcileClosedRecords([{ orderId: 'close-1', closedPnl: -100, updatedTime: 1 }], 9900);
assert.strictEqual(newly.length, 1);
newly = risk.reconcileClosedRecords([{ orderId: 'close-1', closedPnl: -100, updatedTime: 1 }], 9900);
assert.strictEqual(newly.length, 0);
assert.strictEqual(risk.getStatus().dailyNetPnl, -100);
risk.reconcileClosedRecords([{ orderId: 'close-2', closedPnl: -101, updatedTime: 2 }], 9799);
assert.strictEqual(risk.checkDailyLoss(0, 9799).passed, false);
const intraday = risk.checkDailyLoss(0, 9700);
assert.strictEqual(intraday.passed, false);
assert.match(intraday.reason, /Intraday equity drawdown/);
console.log('persistent cooldown and idempotent daily circuit breaker verified');
